name: buildproject
on:
  workflow_dispatch:
  push:
    branches:
      - cicd
permissions:
  contents: write

jobs:
  run_unit_test:
    name: Run Unit tests
    runs-on: ubuntu-latest
  steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 11 for x64
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        architecture: x64
    - name: Grant Permissions to gradlew
      run: chmod +x gradlew
    - name: Test
      run: gradle test --tests "*"